create extension if not exists pgcrypto;

create table if not exists public.spin_events (
  id bigint generated by default as identity primary key,
  device_id uuid not null,
  session_id uuid not null,
  round_number integer not null check (round_number > 0),
  player text not null check (player in ('P1', 'P2')),
  part_text varchar(140) not null,
  action_text varchar(140) not null,
  timer_text varchar(140) not null,
  created_at timestamptz not null,
  received_at timestamptz not null default timezone('utc', now())
);

create index if not exists spin_events_created_at_idx on public.spin_events (created_at desc);
create index if not exists spin_events_device_id_idx on public.spin_events (device_id);
create index if not exists spin_events_session_id_idx on public.spin_events (session_id);

alter table public.spin_events enable row level security;
